// The non-HTML machine surfaces, and the zone Worker route that now serves
// them.
//
// WHY THIS EXISTS, and why it changed shape. Measured 2026-09-03: the Pages
// ASSET layer 403s requests whose User-Agent is a Python stdlib default
// (`error code: 1010`), while paths handled by CODE answer normally. The
// first fix tried was a Pages Function (`functions/[[path]].js`, bounded by
// `dist/_routes.json`) — that did NOT work, because Cloudflare Pages' Browser
// Integrity Check runs in front of the whole Pages project, Functions
// included. The actual fix moves these paths off Pages entirely: they are
// compiled into `worker/surfaces.generated.js` and served by the zone
// Worker (`worker/beacon.js`), routed there directly in `wrangler.toml`. This
// file tests that Worker route instead of the removed Function.
//
// PHASE: standalone — boots its own `wrangler dev` worker (same pattern as
// x402-settlement.test.mjs / x402-solana.test.mjs / alerts.test.mjs) rather
// than joining the shared one, because it needs no D1 fixtures or dev vars at
// all: the default boot is enough. It is first because it is the cheapest
// thing in the run. `worker/beacon.js` cannot be imported directly in plain
// Node — it imports the workerd built-in `cloudflare:email`, which the
// default ESM loader refuses (`Only URLs with a scheme in: file, data, and
// node are supported`) — so a real (but fast, ~2 s) worker boot is the only
// way to exercise its routing. No network beyond localhost (AF-06).

import test, { before, after, describe } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, extname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { parse as tomlParse } from 'smol-toml';
import { bootWorker, client } from './harness.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'dist');

// The PRODUCTION build, run here rather than assumed: dist/ is gitignored, and
// a developer whose last run was `build:demo` has localhost baked in. The
// three overrides that change the output are stripped, so this is the same
// anywhere.
const buildEnv = { ...process.env };
delete buildEnv.BEACON_URL;
delete buildEnv.SITE_HOST;
delete buildEnv.API_HOST;
execFileSync(process.execPath, ['build.mjs'], { cwd: ROOT, env: buildEnv, stdio: 'pipe' });

// GENERATED by the build just above — a dynamic import, not a static one, so
// the ESM loader cannot resolve it before execFileSync has run (static
// imports are hoisted and evaluated ahead of this module's own top-level
// code).
const { default: SURFACES } = await import(
  pathToFileURL(join(ROOT, 'worker', 'surfaces.generated.js')).href
);

const HOST = 'toolshed.lemon-agent.dev';

// What each extension is expected to advertise — independent of SURFACES
// itself, so this is a real check on the generated content-types rather than
// a tautology against the same map.
const EXPECTED_CONTENT_TYPE = {
  '.txt': 'text/plain; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
};

let worker;
let api;

before(async () => {
  worker = await bootWorker();
  api = client(worker);
});

after(async () => {
  await worker?.stop();
});

describe('build.mjs', () => {
  test('no longer emits dist/_routes.json', () => {
    assert.equal(existsSync(join(DIST, '_routes.json')), false);
  });

  test('the removed Pages Function is gone', () => {
    assert.equal(existsSync(join(ROOT, 'functions', '[[path]].js')), false);
  });
});

describe('worker/surfaces.generated.js', () => {
  test('does not include the browser surface', () => {
    assert.ok(!('/index.html' in SURFACES), '/index.html must stay Pages-only');
    assert.ok(!('/' in SURFACES), '/ must stay Pages-only');
  });

  test('at least the five discovery surfaces are present', () => {
    for (const p of ['/llms.txt', '/llms-full.txt', '/openapi.json', '/catalog.json', '/robots.txt']) {
      assert.ok(p in SURFACES, `worker/surfaces.generated.js is missing ${p}`);
    }
  });

  test('every body is byte-identical to its dist/ copy', () => {
    for (const [path, surface] of Object.entries(SURFACES)) {
      const distBytes = readFileSync(join(DIST, path.slice(1)));
      assert.ok(
        Buffer.from(surface.body).equals(distBytes),
        `${path}: worker/surfaces.generated.js body differs from dist${path}`
      );
    }
  });

  test('content-type follows the file-extension convention', () => {
    for (const [path, surface] of Object.entries(SURFACES)) {
      const expected = EXPECTED_CONTENT_TYPE[extname(path)];
      assert.ok(expected, `${path}: no expected content-type registered for this extension`);
      assert.equal(surface.contentType, expected, `${path}: unexpected content-type`);
    }
  });
});

describe('GET/HEAD/POST on a machine surface, served by the Worker', () => {
  for (const [path, surface] of Object.entries(SURFACES)) {
    test(`GET ${path} matches dist${path} byte for byte, with the right headers`, async () => {
      const res = await api.get(path);
      assert.equal(res.status, 200);
      const body = Buffer.from(await res.arrayBuffer());
      assert.ok(
        body.equals(readFileSync(join(DIST, path.slice(1)))),
        `${path}: served bytes differ from dist${path}`
      );
      assert.equal(res.headers.get('content-type'), surface.contentType);
      assert.equal(res.headers.get('cache-control'), 'public, max-age=0, must-revalidate');
      assert.equal(res.headers.get('x-content-type-options'), 'nosniff');
      assert.equal(res.headers.get('access-control-allow-origin'), '*');
    });

    test(`HEAD ${path} returns the same headers with an empty body`, async () => {
      const res = await api.request(path, { method: 'HEAD' });
      assert.equal(res.status, 200);
      const body = Buffer.from(await res.arrayBuffer());
      assert.equal(body.length, 0, `${path}: HEAD must answer an empty body`);
      assert.equal(res.headers.get('content-type'), surface.contentType);
      assert.equal(res.headers.get('cache-control'), 'public, max-age=0, must-revalidate');
      assert.equal(res.headers.get('x-content-type-options'), 'nosniff');
    });

    test(`POST ${path} is 405 with an allow header`, async () => {
      const res = await api.post(path, 'x');
      assert.equal(res.status, 405);
      assert.equal(res.headers.get('allow'), 'GET, HEAD');
    });
  }
});

describe('wrangler.toml routes every surface to this Worker', () => {
  const toml = tomlParse(readFileSync(join(ROOT, 'wrangler.toml'), 'utf8'));
  const routes = (toml.routes || []).filter((r) => r.zone_name === 'lemon-agent.dev');

  // Cloudflare route-pattern grammar, scoped to this one host: an exact path,
  // or a path prefix ending `/*`.
  const covers = (pattern, path) => {
    const prefix = `${HOST}/`;
    if (!pattern.startsWith(prefix)) return false;
    const routePath = `/${pattern.slice(prefix.length)}`;
    return routePath.endsWith('/*') ? path.startsWith(routePath.slice(0, -1)) : routePath === path;
  };

  for (const path of Object.keys(SURFACES)) {
    test(`${path} has a matching wrangler.toml route for ${HOST}`, () => {
      const matched = routes.some((r) => covers(r.pattern, path));
      assert.ok(matched, `no wrangler.toml route for ${HOST} covers ${path}`);
    });
  }
});
